# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b9c861a-a7c3-431c-b753-8fb7ef53069a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4131a90f-6d08-4560-b299-61091ec866e7";
      fsType = "ext4";
    };

  fileSystems."/home/houssem/Desktop" =
    { device = "mount_host_desktop";
      fsType = "virtiofs";
    };

  fileSystems."/home/houssem/Pictures" =
    { device = "mount_host_pictures";
      fsType = "virtiofs";
    };

  fileSystems."/home/houssem/Utilities" =
    { device = "mount_utilities";
      fsType = "virtiofs";
    };

  fileSystems."/home/houssem/Documents" =
    { device = "mount_host_documents";
      fsType = "virtiofs";
    };

  fileSystems."/home/houssem/Downloads" =
    { device = "mount_host_downloads";
      fsType = "virtiofs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
